version: "2"

services:
  hbase-master:
    image: blueskyareahm/hbase-base:2.1.3
    command: master
    ports:
      - 16000:16000
      - 16010:16010

  hbase-regionserver:
    image: blueskyareahm/hbase-base:2.1.3
    command: regionserver
    ports:
      - 16030:16030
      - 16201:16201
      - 16301:16301

  zookeeper:
    image: blueskyareahm/hbase-zookeeper:3.4.13
    ports:
      - 2181:2181

  jupyter:
    container_name: ex05-jupyter
    build:
      context: ./jupyter
    restart: no
    ports:
      - 8888:8888
    user: root
    volumes:
      - ./:/home/jovyan
    command: ["start.sh", "jupyter", "notebook", "--NotebookApp.token=''"]
